name: Wake up Apps

on:
  schedule:
    - cron: '0 8,20 * * *' # Tourne à 8h et 20h pour être sûre
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up apps
        run: |
          wget --spider --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" https://solaridehorizon.streamlit.app/
          wget --spider --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" https://creusecineplus.streamlit.app/
